###############################################################################
# File: extract-compile-commands.py
###############################################################################
"""Print include commands from an Exnihilo build directory.

The single argument should be the path to the 'compile_commands.json' file
generated by CMake.
"""
import json
import sys
###############################################################################

def process_and_print(cmd_text):
    for token in cmd_text.split():
        if token.startswith('-I'):
            print(token, '\\')

def main(json_filename):
    with open(json_filename) as f:
        contents = json.load(f)

    for cmd in contents:
        if cmd['file'].endswith('omnibus.cc'):
            process_and_print(cmd['command'])
            break

#-----------------------------------------------------------------------------#
if __name__ == '__main__':
    (_, *args) = sys.argv
    main(*args)

###############################################################################
# end of extract-compile-commands.py
###############################################################################
