# GNU C++11 (MacPorts gcc5 5.3.0_0) version 5.3.0 (x86_64-apple-darwin15)
#	compiled by GNU C version 5.3.0, GMP version 6.1.0, MPFR version 3.1.3, MPC version 1.0.3
# GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
# options passed:  -D__DYNAMIC__ poly.cc -fPIC -mmacosx-version-min=10.11.4
# -mtune=core2 -auxbase-strip poly.S -O2 -Wall -Wextra -std=c++11
# -fverbose-asm
# options enabled:  -Wnonportable-cfstrings -fPIC
# -faggressive-loop-optimizations -falign-labels
# -fasynchronous-unwind-tables -fauto-inc-dec -fbranch-count-reg
# -fcaller-saves -fchkp-check-incomplete-type -fchkp-check-read
# -fchkp-check-write -fchkp-instrument-calls -fchkp-narrow-bounds
# -fchkp-optimize -fchkp-store-bounds -fchkp-use-static-bounds
# -fchkp-use-static-const-bounds -fchkp-use-wrappers
# -fcombine-stack-adjustments -fcommon -fcompare-elim -fcprop-registers
# -fcrossjumping -fcse-follow-jumps -fdefer-pop
# -fdelete-null-pointer-checks -fdevirtualize -fdevirtualize-speculatively
# -fearly-inlining -feliminate-unused-debug-types -fexceptions
# -fexpensive-optimizations -fforward-propagate -ffunction-cse -fgcse
# -fgcse-lm -fgnu-unique -fguess-branch-probability -fhoist-adjacent-loads
# -fident -fif-conversion -fif-conversion2 -findirect-inlining -finline
# -finline-atomics -finline-functions-called-once -finline-small-functions
# -fipa-cp -fipa-cp-alignment -fipa-icf -fipa-icf-functions
# -fipa-icf-variables -fipa-profile -fipa-pure-const -fipa-ra
# -fipa-reference -fipa-sra -fira-hoist-pressure -fira-share-save-slots
# -fira-share-spill-slots -fisolate-erroneous-paths-dereference -fivopts
# -fkeep-static-consts -fleading-underscore -flifetime-dse -flra-remat
# -flto-odr-type-merging -fmath-errno -fmerge-constants
# -fmerge-debug-strings -fmove-loop-invariants -fnext-runtime
# -fobjc-abi-version= -fomit-frame-pointer -foptimize-sibling-calls
# -foptimize-strlen -fpartial-inlining -fpeephole -fpeephole2
# -fprefetch-loop-arrays -free -freg-struct-return -freorder-blocks
# -freorder-blocks-and-partition -freorder-functions -frerun-cse-after-loop
# -fsched-critical-path-heuristic -fsched-dep-count-heuristic
# -fsched-group-heuristic -fsched-interblock -fsched-last-insn-heuristic
# -fsched-rank-heuristic -fsched-spec -fsched-spec-insn-heuristic
# -fsched-stalled-insns-dep -fschedule-fusion -fschedule-insns2
# -fsemantic-interposition -fshow-column -fshrink-wrap -fsigned-zeros
# -fsplit-ivs-in-unroller -fsplit-wide-types -fssa-phiopt -fstdarg-opt
# -fstrict-aliasing -fstrict-overflow -fstrict-volatile-bitfields
# -fsync-libcalls -fthread-jumps -ftoplevel-reorder -ftrapping-math
# -ftree-bit-ccp -ftree-builtin-call-dce -ftree-ccp -ftree-ch
# -ftree-coalesce-vars -ftree-copy-prop -ftree-copyrename -ftree-cselim
# -ftree-dce -ftree-dominator-opts -ftree-dse -ftree-forwprop -ftree-fre
# -ftree-loop-if-convert -ftree-loop-im -ftree-loop-ivcanon
# -ftree-loop-optimize -ftree-parallelize-loops= -ftree-phiprop -ftree-pre
# -ftree-pta -ftree-reassoc -ftree-scev-cprop -ftree-sink -ftree-slsr
# -ftree-sra -ftree-switch-conversion -ftree-tail-merge -ftree-ter
# -ftree-vrp -funit-at-a-time -funwind-tables -fverbose-asm
# -fzero-initialized-in-bss -gstrict-dwarf -m128bit-long-double -m64
# -m80387 -malign-stringops -matt-stubs -mconstant-cfstrings
# -mfancy-math-387 -mfp-ret-in-387 -mfxsr -mieee-fp -mlong-double-80 -mmmx
# -mno-sse4 -mpush-args -mred-zone -msse -msse2 -msse3 -mvzeroupper

	.section __TEXT,__text_cold,regular,pure_instructions
LCOLDB0:
	.text
LHOTB0:
	.align 4,0x90
	.globl __Z15execute_dynamicRK8Operatorii
__Z15execute_dynamicRK8Operatorii:
LFB56:
	movq	(%rdi), %rax	# op_2(D)->_vptr.Operator, op_2(D)->_vptr.Operator
	movq	16(%rax), %rax	# MEM[(int (*__vtbl_ptr_type) () *)_3 + 16B], MEM[(int (*__vtbl_ptr_type) () *)_3 + 16B]
	jmp	*%rax	# MEM[(int (*__vtbl_ptr_type) () *)_3 + 16B]
LFE56:
	.section __TEXT,__text_cold,regular,pure_instructions
LCOLDE0:
	.text
LHOTE0:
	.section __TEXT,__text_cold,regular,pure_instructions
LCOLDB1:
	.text
LHOTB1:
	.align 4,0x90
	.globl __Z19execute_two_dynamicRK8Operatori
__Z19execute_two_dynamicRK8Operatori:
LFB57:
	movq	(%rdi), %rax	# op_2(D)->_vptr.Operator, op_2(D)->_vptr.Operator
	movq	24(%rax), %rax	# MEM[(int (*__vtbl_ptr_type) () *)_3 + 24B], MEM[(int (*__vtbl_ptr_type) () *)_3 + 24B]
	jmp	*%rax	# MEM[(int (*__vtbl_ptr_type) () *)_3 + 24B]
LFE57:
	.section __TEXT,__text_cold,regular,pure_instructions
LCOLDE1:
	.text
LHOTE1:
	.section __TEXT,__text_cold,regular,pure_instructions
LCOLDB2:
	.text
LHOTB2:
	.align 4,0x90
	.globl __Z14execute_staticRK8Operatorii
__Z14execute_staticRK8Operatorii:
LFB58:
	movl	8(%rdi), %ecx	# MEM[(Operator_Type *)op_2(D) + 8B], D.5920
	cmpl	$1, %ecx	#, D.5920
	je	L5	#,
	jb	L6	#,
	cmpl	$2, %ecx	#, D.5920
	jne	L12	#,
	movl	%esi, %eax	# left, D.5921
	imull	%edx, %eax	# right, D.5921
	ret
	.align 4,0x90
L12:
	subq	$8, %rsp	#,
LCFI0:
	call	__ZSt9terminatev	#
	.align 4,0x90
L6:
LCFI1:
	leal	(%rsi,%rdx), %eax	#, D.5921
	ret
	.align 4,0x90
L5:
	movl	%esi, %eax	# left, D.5921
	subl	%edx, %eax	# right, D.5921
	ret
LFE58:
	.section __TEXT,__text_cold,regular,pure_instructions
LCOLDE2:
	.text
LHOTE2:
	.section __TEXT,__text_cold,regular,pure_instructions
LCOLDB3:
	.text
LHOTB3:
	.align 4,0x90
	.globl __Z23execute_template_staticRK8Operatorii
__Z23execute_template_staticRK8Operatorii:
LFB59:
	movl	8(%rdi), %eax	# op_4(D)->b_type, D.5938
	cmpl	$1, %eax	#, D.5938
	je	L17	#,
	jb	L17	#,
	cmpl	$2, %eax	#, D.5938
	jne	L20	#,
L17:
	movq	(%rdi), %rax	# MEM[(int (*__vtbl_ptr_type) () * *)op_4(D)], MEM[(int (*__vtbl_ptr_type) () * *)op_4(D)]
	movq	16(%rax), %rax	#, MEM[(int (*__vtbl_ptr_type) () *)_47 + 16B]
	jmp	*%rax	# MEM[(int (*__vtbl_ptr_type) () *)_47 + 16B]
	.align 4,0x90
L20:
	subq	$8, %rsp	#,
LCFI2:
	call	__ZSt9terminatev	#
LFE59:
	.section __TEXT,__text_cold,regular,pure_instructions
LCOLDE3:
	.text
LHOTE3:
	.section __TEXT,__text_cold,regular,pure_instructions
LCOLDB4:
	.text
LHOTB4:
	.align 4,0x90
	.globl __Z27execute_two_template_staticRK8Operatori
__Z27execute_two_template_staticRK8Operatori:
LFB60:
	movl	8(%rdi), %eax	# op_4(D)->b_type, D.5958
	cmpl	$1, %eax	#, D.5958
	je	L25	#,
	jb	L25	#,
	cmpl	$2, %eax	#, D.5958
	jne	L28	#,
L25:
	movq	(%rdi), %rax	# MEM[(int (*__vtbl_ptr_type) () * *)op_4(D)], MEM[(int (*__vtbl_ptr_type) () * *)op_4(D)]
	movq	24(%rax), %rax	#, MEM[(int (*__vtbl_ptr_type) () *)_46 + 24B]
	jmp	*%rax	# MEM[(int (*__vtbl_ptr_type) () *)_46 + 24B]
	.align 4,0x90
L28:
	subq	$8, %rsp	#,
LCFI3:
	call	__ZSt9terminatev	#
LFE60:
	.section __TEXT,__text_cold,regular,pure_instructions
LCOLDE4:
	.text
LHOTE4:
	.section __TEXT,__eh_frame,coalesced,no_toc+strip_static_syms+live_support
EH_frame1:
	.set L$set$0,LECIE1-LSCIE1
	.long L$set$0
LSCIE1:
	.long	0
	.byte	0x1
	.ascii "zR\0"
	.byte	0x1
	.byte	0x78
	.byte	0x10
	.byte	0x1
	.byte	0x10
	.byte	0xc
	.byte	0x7
	.byte	0x8
	.byte	0x90
	.byte	0x1
	.align 3
LECIE1:
LSFDE1:
	.set L$set$1,LEFDE1-LASFDE1
	.long L$set$1
LASFDE1:
	.long	LASFDE1-EH_frame1
	.quad	LFB56-.
	.set L$set$2,LFE56-LFB56
	.quad L$set$2
	.byte	0
	.align 3
LEFDE1:
LSFDE3:
	.set L$set$3,LEFDE3-LASFDE3
	.long L$set$3
LASFDE3:
	.long	LASFDE3-EH_frame1
	.quad	LFB57-.
	.set L$set$4,LFE57-LFB57
	.quad L$set$4
	.byte	0
	.align 3
LEFDE3:
LSFDE5:
	.set L$set$5,LEFDE5-LASFDE5
	.long L$set$5
LASFDE5:
	.long	LASFDE5-EH_frame1
	.quad	LFB58-.
	.set L$set$6,LFE58-LFB58
	.quad L$set$6
	.byte	0
	.byte	0x4
	.set L$set$7,LCFI0-LFB58
	.long L$set$7
	.byte	0xe
	.byte	0x10
	.byte	0x4
	.set L$set$8,LCFI1-LCFI0
	.long L$set$8
	.byte	0xe
	.byte	0x8
	.align 3
LEFDE5:
LSFDE7:
	.set L$set$9,LEFDE7-LASFDE7
	.long L$set$9
LASFDE7:
	.long	LASFDE7-EH_frame1
	.quad	LFB59-.
	.set L$set$10,LFE59-LFB59
	.quad L$set$10
	.byte	0
	.byte	0x4
	.set L$set$11,LCFI2-LFB59
	.long L$set$11
	.byte	0xe
	.byte	0x10
	.align 3
LEFDE7:
LSFDE9:
	.set L$set$12,LEFDE9-LASFDE9
	.long L$set$12
LASFDE9:
	.long	LASFDE9-EH_frame1
	.quad	LFB60-.
	.set L$set$13,LFE60-LFB60
	.quad L$set$13
	.byte	0
	.byte	0x4
	.set L$set$14,LCFI3-LFB60
	.long L$set$14
	.byte	0xe
	.byte	0x10
	.align 3
LEFDE9:
	.constructor
	.destructor
	.align 1
	.subsections_via_symbols
